### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by brock** [ncsa/Polyglot#1]
Hey @mchenry 

Do you have a readme in markdown format we could add? Even if it were to just contain a link to the homepage on open-source would help.

**Comment by mchenry** [comment]
http://opensource.ncsa.illinois.edu/projects/artifacts/POL/2.1.0-SNAPSHOT/documentation/manual/

Kenton McHenry, Ph.D.
Senior Research Scientist, Adjunct Assistant Professor of Computer Science
Innovative Software and Data Analysis Division (http://isda.ncsa.illinois.eduhttp://isda.ncsa.illinois.edu/)
National Center for Supercomputing Applications

On Sep 10, 2015, at 2:05 PM, Brock Angelo notifications@github.com wrote:

Hey @mchenryhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mchenry&d=AwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=GjsL3GQZwCu3V4ba35Wa71q2YP8DOANBJRNLzPb6PjA&m=zD0JQf9aSm6rCa_eUfP0VbWLkMad-36g10VEEAiAmiY&s=nqF4BVQc4oDDfnQZ4TLPxjocfEMcEDV9dsxlkR7SEtA&e=

Do you have a readme in markdown format we could add? Even if it were to just contain a link to the homepage on open-source would help.

**Comment by brock** [comment]
Thanks @mchenry 
I've added it to the project title and description for now. If I were to also add a README.md with a link to the documentation, would it be best to submit a pull request through open-source or here?

**Comment by mchenry** [comment]
Yes please.

Kenton McHenry, Ph.D.
Senior Research Scientist, Adjunct Assistant Professor of Computer Science
Innovative Software and Data Analysis Division (http://isda.ncsa.illinois.eduhttp://isda.ncsa.illinois.edu/)
National Center for Supercomputing Applications

On Sep 11, 2015, at 1:50 PM, Brock Angelo <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks @mchenryhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mchenry&d=AwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=GjsL3GQZwCu3V4ba35Wa71q2YP8DOANBJRNLzPb6PjA&m=O9A9_2Ti4KhHYe5sngAgdH_5ZPMopAzyhxDMvNVCNBE&s=HlEPczmCpTRD_mL8QM6IKU8vnb1A7WDZzawZxuNVp5Q&e=
I've added it to the project title and description for now. If I were to also add a README.md with a link to the documentation, would it be best to submit a pull request through open-source or here?

**Comment by brock** [comment]
README added and will get pushed to Github
https://opensource.ncsa.illinois.edu/stash/projects/POL/repos/polyglot/pull-requests/57/overview
